### ISSUE TITLE
feat: change from bash to sh, and add clarity in readme about dependencies

### ISSUE THREAD

**Issue by lrstanley** [oufm/packelf#1]
Stumbled on the askubuntu post looking for a solution similar to this. Couple of things that might be good to call out, as well as think about:

1. Use `sh` rather than `bash` in the generated file -- `sh` is more widely available (e.g. `alpine` doesn't include bash by default, but is a very popular container image).
2. Would be good to call out in the readme how the process works. E.g. the mktemp approach is simple, however it has some potential downsides that users may want to know about.
3. Call out the list of system dependencies that would be needed on the target system, e.g:
    - `sh`
    - `touch`
    - `mktemp`
    - `tar` (with gzip support)
    - etc
4. Might be good to call out that it does a decompression on the initial execution, which means startup times will be much worse (though possibly acceptable). For example, with a source binary of `150mb` (without including dependencies) on a fairly beefy system:

```
# original source
$ time deno -h
[...]

real    0m0.004s
user    0m0.004s
sys     0m0.000s
```

```
# packelf/targz wrapped:
$ time deno.test -h
[...]

real    0m0.858s
user    0m0.776s
sys     0m0.293s
```

For single calls to misc programs, not an issue, but it's about 210x slower (on my 24-core system), which easily adds up for simple looped calls to the wrapped version.

**Comment by Mte90** [comment]
Reading the code and testing the tool maybe should use `!#/usr/bin/env sh` as shebang in this way is more standard.

Also doesn't keep the tmp folder between execution, maybe generate the tool without that code that remove the folder and uses the already exported can speed up.

**Comment by oufm** [comment]
It uses `sh` now. And dependence was added:
https://github.com/oufm/packelf/tree/master?tab=readme-ov-file#dependence
